# Generated by Django 5.1.2 on 2024-11-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0002_rename_appointment_file_appointmentdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='appointmentdetail',
        ),
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AppointmentDetail',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
