# Generated by Django 5.1.2 on 2024-11-08 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0005_alter_appointment_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=50)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mycalendar.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycalendar.appointment')),
            ],
        ),
    ]
