# Generated by Django 5.1.2 on 2024-11-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0007_direction_project_appointment_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='slug',
            field=models.SlugField(default='null', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='null', unique=True),
            preserve_default=False,
        ),
    ]
