# Generated by Django 5.1.2 on 2024-12-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0009_alter_direction_description_and_more'),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='contact',
            field=models.ManyToManyField(blank=True, null=True, to='userauth.profile'),
        ),
    ]
