# Generated by Django 5.1.2 on 2024-12-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0010_appointment_contact'),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='contact',
            field=models.ManyToManyField(to='userauth.profile'),
        ),
    ]
