# Generated by Django 5.1.2 on 2024-12-17 07:57

import mycalendar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0011_alter_appointment_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentfile',
            name='file',
            field=models.FileField(upload_to=mycalendar.models.file_upload_name),
        ),
    ]
